### ISSUE TITLE
Error: HTTP error! status: 400

### ISSUE THREAD

**Issue by raufbisov** [vasilecampeanu/obsidian-weaver#44]
After 15 minutes of using ChatGPT it responds with "Error: HTTP error! status: 400"
![image](https://github.com/vasilecampeanu/obsidian-weaver/assets/62175802/99172692-ecc7-4cfa-a986-85b36f6b7f6f)
There is a workaround where you disable the context feature (the green button in the upper right). Still, it would be nice if I could keep this feature.
![image](https://github.com/vasilecampeanu/obsidian-weaver/assets/62175802/4f20090b-8a01-4929-8271-4392c146c242)

**Comment by vasilecampeanu** [comment]
I think this is caused because I haven't set a limit for the context of the chat. So, every time you ask something, all the previous messages will be sent to the API. ChatGPT has a limited context of 4096 tokens, so exceeding that limit will result in an error. This issue will be fixed, but until 7 July, I am occupied with exams.

**Comment by BumbleBeeElegy** [comment]
+1 to this request. When working through some complex conversations that build on each other, that context is really important.

I'm really enjoying this extension so far. 😄

**Comment by zachshallbetter** [comment]
Attached response error and related issue #30 

```
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4610 tokens (1610 in the messages, 3000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
```
